### ISSUE TITLE
这么好的项目为啥不更新了呀？

### ISSUE THREAD

**Issue by sonofmagic** [JChehe/GSAP_CN#1]

**Comment by JChehe** [comment]
@sonofmagic 应该已经把主要部分（TweenLite、TweenMax、TimelineLite、TimelineMax）翻译完成了，其他部分（插件）并没有翻译的打算。最近也比较少搞动画方面，所以暂时没继续弄下去。明年再看看，大家有兴趣也可以一起维护。
